
    version: "3.2" # Version of docker-compose to use
    services:
      cars-db: # Name of the service
        image: mysql:8 # Image (local or public) to create the container from
        ports:
          - "3309:3306" # Exposed host port : container port
        volumes:
          # Copy the setup file from your the local directory
          # into the init db dir for initialization
          - ./:/docker-entrypoint-initdb.d
          # Mount a local directory to persist the database after
          # removal of the container.  Note, actual volume is
          # defined below
          - cars-data:/var/lib/mysql
        environment: # Environment variables required by the image
          MYSQL_ROOT_PASSWORD: my-secret-pw
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    
    # Add more services here
    
    volumes: # Volumes that can be shared by all services (must exist on the service declaration.)  You can include the path to your development source code as well.  Check the Docker docs for more info.
      cars-data:
        driver: local